name: Build MoeKoeMusic Docker Image for udocker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build old Docker format image (compatible with udocker)
        run: |
          docker build --format=docker -t moekoe:local .

      - name: Save image to tar
        run: |
          docker save -o moekoe.tar moekoe:local

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moekoe-docker-image
          path: moekoe.tar
